//! Extended binary Golay code `[24, 12, 8]`.
//!
//! Construction: the perfect binary Golay code `[23, 12, 7]` is the
//! quadratic-residue cyclic code of length 23, generated by one of the two
//! degree-11 factors of `x^23 - 1` over F₂:
//!
//! ```text
//! x^23 + 1 = (x + 1) · g1(x) · g2(x)
//! g1(x) = x^11 + x^9 + x^7 + x^6 + x^5 + x + 1        (0xAE3)
//! g2(x) = x^11 + x^10 + x^6 + x^5 + x^4 + x^2 + 1     (0xC75)
//! ```
//!
//! Appending an overall parity bit (bit 23) yields the extended code
//! `[24, 12, 8]`, whose weight enumerator is `1 + 759·x^8 + 2576·x^12 +
//! 759·x^16 + x^24` (Conway & Sloane, *SPLAG*, ch. 10). The G1 test-suite
//! asserts exactly this distribution, so a wrong generator polynomial cannot
//! survive testing.
//!
//! Codewords are stored as `u32` with coordinate `i` in bit `i` (bits 0–22:
//! cyclic part, bit 23: parity extension).

/// Generator polynomial `g2(x) = x^11 + x^10 + x^6 + x^5 + x^4 + x^2 + 1`.
pub const GEN_POLY: u32 = 0xC75;

/// The reciprocal factor `g1(x) = x^11 + x^9 + x^7 + x^6 + x^5 + x + 1`.
pub const GEN_POLY_RECIPROCAL: u32 = 0xAE3;

/// Carry-less (GF(2)) polynomial multiplication, **low 64 bits only**:
/// bits of the product at position ≥ 64 are silently dropped, so the result
/// is exact iff `deg a + deg b < 64` (true for every use in this crate,
/// where products have degree ≤ 23).
pub fn clmul(mut a: u64, mut b: u64) -> u64 {
    let mut acc = 0u64;
    while b != 0 {
        if b & 1 == 1 {
            acc ^= a;
        }
        a <<= 1;
        b >>= 1;
    }
    acc
}

/// The extended binary Golay code `[24, 12, 8]`.
///
/// Single flat storage: the 4096 codewords (16 KiB) laid out weight-major,
/// ascending within each weight bucket, plus a 26-entry offset table.
/// Membership is a binary search within the word's weight bucket; Phase 2
/// (Adoul–Barth) iterates buckets contiguously in hot loops.
pub struct Golay {
    flat: Vec<u32>,
    offsets: [usize; 26],
}

impl Golay {
    /// Build the code by encoding all 2^12 messages.
    ///
    /// `m(x) · g2(x)` has degree ≤ 22, so no modular reduction is needed:
    /// the products *are* the cyclic codewords. The map is injective because
    /// F₂[x] is an integral domain (the G1 suite additionally asserts the
    /// 4096 stored words are pairwise distinct).
    pub fn new() -> Self {
        let mut flat: Vec<u32> = (0u32..4096)
            .map(|m| {
                let c = clmul(m as u64, GEN_POLY as u64) as u32;
                debug_assert!(c < (1 << 23));
                let parity = c.count_ones() & 1;
                c | (parity << 23)
            })
            .collect();
        flat.sort_unstable_by_key(|&c| (c.count_ones(), c));

        let mut offsets = [0usize; 26];
        for &c in &flat {
            offsets[c.count_ones() as usize + 1] += 1;
        }
        for w in 0..25 {
            offsets[w + 1] += offsets[w];
        }
        Self { flat, offsets }
    }

    /// Membership test (exact): binary search within the weight bucket.
    /// Total over all of `u32` — words with bits ≥ 24 or weight > 24 are
    /// simply not codewords.
    #[inline]
    pub fn contains(&self, word: u32) -> bool {
        let w = word.count_ones() as usize;
        if w > 24 {
            return false;
        }
        self.flat[self.offsets[w]..self.offsets[w + 1]]
            .binary_search(&word)
            .is_ok()
    }

    /// All 4096 codewords, in a fixed deterministic order
    /// (weight-major, ascending within each weight).
    pub fn codewords(&self) -> &[u32] {
        &self.flat
    }

    /// Codewords of the given Hamming weight, ascending
    /// (non-empty only for weights 0, 8, 12, 16, 24). Total function:
    /// any `weight > 24` yields an empty slice, never a panic.
    pub fn of_weight(&self, weight: usize) -> &[u32] {
        if weight > 24 {
            return &[];
        }
        &self.flat[self.offsets[weight]..self.offsets[weight + 1]]
    }

    /// Rank of a codeword in the fixed [`Golay::codewords`] order
    /// (weight-major, ascending within a weight), or `None` if `word` is
    /// not a codeword. `codewords()[rank] == word` — this order is part of
    /// the LLVQ index format and must never change.
    pub fn rank(&self, word: u32) -> Option<usize> {
        let w = word.count_ones() as usize;
        if w > 24 {
            return None;
        }
        let bucket = &self.flat[self.offsets[w]..self.offsets[w + 1]];
        bucket.binary_search(&word).ok().map(|i| self.offsets[w] + i)
    }

    /// Rank of a codeword *within its weight bucket* (ascending), or `None`.
    pub fn rank_in_weight(&self, word: u32) -> Option<usize> {
        let w = word.count_ones() as usize;
        if w > 24 {
            return None;
        }
        self.flat[self.offsets[w]..self.offsets[w + 1]]
            .binary_search(&word)
            .ok()
    }
}

impl Default for Golay {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// `(x+1) · g1 · g2 == x^23 + 1` — proves the generator really is a
    /// factor of `x^23 - 1`, i.e. the code is the QR cyclic code.
    #[test]
    fn generator_factorization() {
        let prod = clmul(
            clmul(GEN_POLY as u64, GEN_POLY_RECIPROCAL as u64),
            0b11, // x + 1
        );
        assert_eq!(prod, (1 << 23) | 1);
    }

    #[test]
    fn code_is_closed_under_xor() {
        let g = Golay::new();
        // Linearity: spot-check closure on a deterministic sample of pairs.
        let cw = g.codewords();
        for i in (0..4096).step_by(97) {
            for j in (0..4096).step_by(89) {
                assert!(g.contains(cw[i] ^ cw[j]));
            }
        }
    }

    #[test]
    fn of_weight_is_total() {
        let g = Golay::new();
        assert!(g.of_weight(25).is_empty());
        assert!(g.of_weight(usize::MAX).is_empty());
        assert!(!g.contains(u32::MAX)); // weight 32 > 24
    }
}
