//! Extended binary Golay code `[24, 12, 8]`.
//!
//! Construction: the perfect binary Golay code `[23, 12, 7]` is the
//! quadratic-residue cyclic code of length 23, generated by one of the two
//! degree-11 factors of `x^23 - 1` over F₂:
//!
//! ```text
//! x^23 + 1 = (x + 1) · g1(x) · g2(x)
//! g1(x) = x^11 + x^9 + x^7 + x^6 + x^5 + x + 1        (0xAE3)
//! g2(x) = x^11 + x^10 + x^6 + x^5 + x^4 + x^2 + 1     (0xC75)
//! ```
//!
//! Appending an overall parity bit (bit 23) yields the extended code
//! `[24, 12, 8]`, whose weight enumerator is `1 + 759·x^8 + 2576·x^12 +
//! 759·x^16 + x^24` (Conway & Sloane, *SPLAG*, ch. 10). The G1 test-suite
//! asserts exactly this distribution, so a wrong generator polynomial cannot
//! survive testing.
//!
//! Codewords are stored as `u32` with coordinate `i` in bit `i` (bits 0–22:
//! cyclic part, bit 23: parity extension).

/// Generator polynomial `g2(x) = x^11 + x^10 + x^6 + x^5 + x^4 + x^2 + 1`.
pub const GEN_POLY: u32 = 0xC75;

/// The reciprocal factor `g1(x) = x^11 + x^9 + x^7 + x^6 + x^5 + x + 1`.
pub const GEN_POLY_RECIPROCAL: u32 = 0xAE3;

/// Carry-less (GF(2)) polynomial multiplication.
pub fn clmul(mut a: u64, mut b: u64) -> u64 {
    let mut acc = 0u64;
    while b != 0 {
        if b & 1 == 1 {
            acc ^= a;
        }
        a <<= 1;
        b >>= 1;
    }
    acc
}

/// The extended binary Golay code `[24, 12, 8]`.
///
/// Holds the full list of 4096 codewords (16 KiB) plus weight-indexed
/// buckets; membership is a binary search. This is small enough to live in
/// L1/L2 and fast enough for exhaustive shell enumeration in the tests and
/// for the Adoul–Barth search of Phase 2, which iterates codewords by weight.
pub struct Golay {
    sorted: Vec<u32>,
    by_weight: Vec<Vec<u32>>,
}

impl Golay {
    /// Build the code by encoding all 2^12 messages.
    ///
    /// `m(x) · g2(x)` has degree ≤ 22, so no modular reduction is needed:
    /// the products *are* the cyclic codewords. The map is injective because
    /// F₂[x] is an integral domain.
    pub fn new() -> Self {
        let mut sorted: Vec<u32> = (0u32..4096)
            .map(|m| {
                let c = clmul(m as u64, GEN_POLY as u64) as u32;
                debug_assert!(c < (1 << 23));
                let parity = c.count_ones() & 1;
                c | (parity << 23)
            })
            .collect();
        sorted.sort_unstable();

        let mut by_weight = vec![Vec::new(); 25];
        for &c in &sorted {
            by_weight[c.count_ones() as usize].push(c);
        }
        Self { sorted, by_weight }
    }

    /// Membership test (exact, by binary search over the 4096 codewords).
    #[inline]
    pub fn contains(&self, word: u32) -> bool {
        self.sorted.binary_search(&word).is_ok()
    }

    /// All 4096 codewords, sorted ascending.
    pub fn codewords(&self) -> &[u32] {
        &self.sorted
    }

    /// Codewords of the given Hamming weight
    /// (non-empty only for weights 0, 8, 12, 16, 24).
    pub fn of_weight(&self, weight: usize) -> &[u32] {
        &self.by_weight[weight]
    }
}

impl Default for Golay {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// `(x+1) · g1 · g2 == x^23 + 1` — proves the generator really is a
    /// factor of `x^23 - 1`, i.e. the code is the QR cyclic code.
    #[test]
    fn generator_factorization() {
        let prod = clmul(
            clmul(GEN_POLY as u64, GEN_POLY_RECIPROCAL as u64),
            0b11, // x + 1
        );
        assert_eq!(prod, (1 << 23) | 1);
    }

    #[test]
    fn code_is_closed_under_xor() {
        let g = Golay::new();
        // Linearity: spot-check closure on a deterministic sample of pairs.
        let cw = g.codewords();
        for i in (0..4096).step_by(97) {
            for j in (0..4096).step_by(89) {
                assert!(g.contains(cw[i] ^ cw[j]));
            }
        }
    }
}
